/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
	nodes: {
		Plane: THREE.Mesh
	}
	materials: {
		steel: THREE.MeshStandardMaterial
	}
}

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>()
	const { nodes, materials } = useGLTF(
		"/3D-gallery/shuriken.glb"
	) as GLTFResult
	return (
		<group ref={group as any} {...props} dispose={null}>
			<mesh
				geometry={nodes.Plane.geometry}
				material={materials.steel}
				rotation={[0, -Math.PI / 4, 0]}
			/>
		</group>
	)
}

useGLTF.preload("/3D-gallery/shuriken.glb")
